seed: 42

name: gpt
mode: predict 
save_dir: checkpoint_gpt/
predict_file_path: prediction_test.jsonl

model:
    path: checkpoint_gpt/trained_model/
    load_fp16: False
    num_beams: 2
    generator:
        path: skt/ko-gpt-trinity-1.2B-v0.5

optimizer:
    lr: 1e-5

tokenizer:
    path: skt/ko-gpt-trinity-1.2B-v0.5



datamodule:
    batch_size: 8
    shuffle: false
    num_workers: 4

    data_dir: data/generation_E
    train_data: training.jsonl
    valid_data: valid.jsonl
    test_data: test.jsonl
    label_file: ''
    
    check_length: false
    max_source_length: 128
    max_target_length: 128
    max_kb_length: 96
    
    prompt_prefix: ''
    prompt_suffix: ''
    task_prompt: ''

agent:
    epochs: 1000
    patience: 5
    model_all_save: false
    predict_after_all_training: false
    predict_after_training: true

print_config: true

